### ISSUE TITLE
未初始化完成运行CrossHud.Current.ShowToast()的异常

### ISSUE THREAD

**Issue by zlyxm** [ennerperez/HudPlugin#1]
在ContentPage页面未完成初始化前运行CrossHud.Current.ShowToast()提示引用了为空的对象,仅ios报错.
似乎是异步实例化CrossHud.Current,而运行CrossHud.Current.ShowToast()跑在了实例化之前导致的

**Comment by ennerperez** [comment]
Sorry, don't understand. can you report it in english?
