### ISSUE TITLE
cancelCallback can't work 

### ISSUE THREAD

**Issue by NaiShengYu** [ennerperez/HudPlugin#4]
var hud = CrossHud.Current;
hud.Show(cancelCallback: cancelDelegate);
the "cancelDelegate" have not implement

**Comment by ennerperez** [comment]
private void cancelDelegate()
        {
            CrossHud.Current?.Dismiss();
        }

        private void buttonHUD_Clicked(object sender, EventArgs e)
        {
            CrossHud.Current?.Show(cancelCaption: "Cancel", cancelCallback: cancelDelegate);
        }
